### PR TITLE
Added python 3.7 and rerendered with conda-build 3.18.8, conda-smithy 3.4.8 and conda-forge-pinning 2019.09.18

### PR DESCRIPTION
**Pull request by thompsonsed**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dirmeier** [comment]
Oh, brilliant! Thanks! Do you want to add yourself as contributor? I recently don't have much resources to maintain OSS

**Comment by thompsonsed** [comment]
> Oh, brilliant! Thanks! Do you want to add yourself as contributor? I recently don't have much resources to maintain OSS

Sure!

**Comment by thompsonsed** [comment]
> Oh, brilliant! Thanks! Do you want to add yourself as contributor? I recently don't have much resources to maintain OSS

Actually, I couldn't figure out how to do this - perhaps you need to add me?

**Comment by dirmeier** [comment]
Ah, I thought I could just add you to the `gpy` team, but it seems that cannot be done. The proper way to do it is, I believe, adding your github handle to `meta.yaml`.

**Pull request merged**
