### PR TITLE
Update to 1.13.1 and skip Python <= 3.8 builds

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by DManowitz** [comment]
@jan-janssen, you might not have noticed this, but GPy >=1.13.0 now indicates [`python_requires=">=3.9"`](https://github.com/SheffieldML/GPy/blob/v.1.13.0/setup.py).

**Comment by jan-janssen** [comment]
> @jan-janssen, you might not have noticed this, but GPy >=1.13.0 now indicates [`python_requires=">=3.9"`](https://github.com/SheffieldML/GPy/blob/v.1.13.0/setup.py).

Correct, this is why I added `skip: true  # [py<=38]`. While for `noarch: python` packages the python version is restricted using `python >=3.9` for all other packages this is achieved by skipping all builds for Python 3.8 and below. At the same time that is also the reason why the initial built from the automated robot failed back in January https://github.com/conda-forge/gpy-feedstock/pull/36 .

**Comment by DManowitz** [comment]
> Correct, this is why I added `skip: true # [py<=38]`. While for `noarch: python` packages the python version is restricted using `python >=3.9` for all other packages this is achieved by skipping all builds for Python 3.8 and below. At the same time that is also the reason why the initial built from the automated robot failed back in January #36 .

Ah.  I hadn't realized about the `noarch` vs others.

**Comment by jan-janssen** [comment]
> Ah. I hadn't realized about the `noarch` vs others.

For more details https://conda-forge.org/docs/maintainer/adding_pkgs/#skipping-builds and https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python : 

> While `noarch: python` does not work with selectors, it does work with version constraints. `skip: True # [py2k]` can be replaced with a constrained python version in the host and run subsections: say `python >=3` instead of just `python`.

**Comment by jan-janssen** [comment]
@DManowitz Can you merge this pull request? This would allow me to merge https://github.com/conda-forge/aalto-boss-feedstock/pull/19 and https://github.com/conda-forge/aalto-boss-feedstock/pull/20

**Comment by dirmeier** [comment]
Hi @jan-janssen , thanks for patching this. Would you be willing to be listed as maintainer of this repository? Since GPy seems not to be actively developed anymore (and I am not using it), we thought to remove this recipe otherwise. Cheers, S

**Comment by jan-janssen** [comment]
> Hi @jan-janssen , thanks for patching this. Would you be willing to be listed as maintainer of this repository? Since GPy seems not to be actively developed anymore (and I am not using it), we thought to remove this recipe otherwise. Cheers, S

Yes, I already added myself as a maintainer in this pull request.

**Comment by dirmeier** [comment]
Great, thanks!

**Pull request merged**
